# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# title: Your awesome title
# email: your-email@domain.com
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# # Build settings
# markdown: kramdown

# Site settings
name: Siphamandla P.S Simelane
description: "Highly Motivated, Quick-Witted Web Developer"
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
github_username: sphasim
# codepen_username: your_codepen_username_goes_here
# facebook_username: your_facebook_username_goes_here
# vk_username: your_vk_username_goes_here
# twitter_username: your_twitter_username_goes_here
# google_plus_username: your_google_plus_username_goes_here
linkedin_username: siphamandla-p-simelane-aa639140
# vine_username:  your_vine_username_goes_here
# instagram_username:  your_instagram_username_goes_here
# flickr_username: your_flickr_username_goes_here
# steam_username: your_steam_username_goes_here
# soundcloud_username:  your_soundcloud_username_goes_here
# stack_of_username: your_stack_overflow_account_id_number_goes_here
# reddit_username: your_reddit_username_goes_here
# medium_username:  your_medium_username_goes_here
# tumblr_username: your_tumblr_username_goes_here
# weibo_username: your_weibo_username_goes_here
# blog_url: "/blog"
email: sphasim@gmail.com
# public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"


avatar: yes
avatar_img_path: "imgs/avatar.jpg"
# You can link to your GitHub image. That way it will get updated 
# automatically whenever you change your GitHub profile picture
# avatar_img_path: "https://avatars2.githubusercontent.com/u/17301305"


front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"

# Build settings
markdown: kramdown
permalink: pretty

